/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ActivityOccurrenceCreationFailure struct {

	// The details of each user's entry, or just the current user's if not run with ACTIVITIES_ADMIN permission
	UserResults []ActivityOccurrenceJoinResult `json:"user_results,omitempty"`
}
