/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ActionResource struct {

	// The category the action is in. All customer specific actions are in the 'custom' category
	Category string `json:"category,omitempty"`

	// The description of the action
	Description string `json:"description"`

	// The name of the action. Used as the unique id for reference
	Name string `json:"name"`

	// A list of tags for searching
	Tags []string `json:"tags,omitempty"`

	// The variables required for the action
	Variables []ActionVariableResource `json:"variables"`
}
