/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AggregateInvoiceReportResource struct {

	Count int64 `json:"count,omitempty"`

	Date string `json:"date,omitempty"`

	Revenue float64 `json:"revenue,omitempty"`

	UserCount int64 `json:"user_count,omitempty"`
}
