/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The definition of an activity parameters: ex: difficulty level
type AvailableSettingResource struct {

	// Whether the setting is advanced. Default: false
	AdvancedOption bool `json:"advanced_option,omitempty"`

	// The default value of the setting (must be in options array). Ex: easy
	DefaultValue string `json:"default_value,omitempty"`

	// The description of the setting: Ex: Choose the difficulty level to show more or less complicated questions (for a trivia activity)
	Description string `json:"description,omitempty"`

	// The unique ID for the setting: Ex: difficulty
	Key string `json:"key"`

	// The textual name of the setting: Ex: Difficulty Level
	Name string `json:"name"`

	// The set of options available for this setting, Ex: easy, medium, hard
	Options []SettingOption `json:"options,omitempty"`

	// The type of the setting value: Ex: TEXT
	Type_ string `json:"type"`
}
