/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type BatchRequest struct {

	// The request body as would be passed to the URI
	Body interface{} `json:"body,omitempty"`

	// Content type used, Ex:(application/json)
	ContentType string `json:"content_type,omitempty"`

	// The HTTP method used, Ex: (GET)
	Method string `json:"method,omitempty"`

	// Time in seconds before process will timeout.  Default is 60.  Range is 1-300
	Timeout int32 `json:"timeout,omitempty"`

	// The oauth token only
	Token string `json:"token,omitempty"`

	// Full URI of REST call
	Uri string `json:"uri,omitempty"`
}
