/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type BreRuleLog struct {

	// Whether the rule ran
	Ran bool `json:"ran,omitempty"`

	// The reason for the rule
	Reason string `json:"reason,omitempty"`

	// The end date of the rule in seconds
	RuleEndDate int64 `json:"rule_end_date,omitempty"`

	// The id of the rule
	RuleId string `json:"rule_id,omitempty"`

	// The name of the rule
	RuleName string `json:"rule_name,omitempty"`

	// The start date of the rule in seconds
	RuleStartDate int64 `json:"rule_start_date,omitempty"`
}
