/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Cart struct {

	AvailableShippingOptions []CartShippingOption `json:"available_shipping_options,omitempty"`

	CountryTax float64 `json:"country_tax,omitempty"`

	Coupons []CouponDefinition `json:"coupons,omitempty"`

	Created int64 `json:"created,omitempty"`

	CurrencyCode string `json:"currency_code,omitempty"`

	DiscountTotal float64 `json:"discount_total,omitempty"`

	ErrorCode int32 `json:"error_code,omitempty"`

	ErrorMessage string `json:"error_message,omitempty"`

	GrandTotal float64 `json:"grand_total,omitempty"`

	Id string `json:"id,omitempty"`

	InvoiceId float64 `json:"invoice_id,omitempty"`

	Items []CartLineItem `json:"items,omitempty"`

	Owner int32 `json:"owner,omitempty"`

	SelectedShippingOptions []CartShippingOption `json:"selected_shipping_options,omitempty"`

	Shippable bool `json:"shippable,omitempty"`

	ShippingAddress *CartShippingAddressRequest `json:"shipping_address,omitempty"`

	ShippingCost float64 `json:"shipping_cost,omitempty"`

	StateTax float64 `json:"state_tax,omitempty"`

	Status string `json:"status,omitempty"`

	Subtotal float64 `json:"subtotal,omitempty"`

	Updated int64 `json:"updated,omitempty"`
}
