/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ChatMessageRequest struct {

	// The content of the message
	Content *interface{} `json:"content"`

	// The type of the message set by the client
	MessageType string `json:"message_type"`
}
