/* 
 * Knetik Platform API Documentation Latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CountryTaxResource struct {

	// The iso3 code of the country, cannot be changed
	CountryIso3 string `json:"country_iso3,omitempty"`

	// The name of the tax
	Name string `json:"name,omitempty"`

	// The tax rate as a percentage to a maximum of two decimal places (1.5 means 1.5%)
	Rate float64 `json:"rate,omitempty"`

	// Whether the tax applies to shipping costs
	TaxShipping bool `json:"tax_shipping,omitempty"`
}
