/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Country struct {

	Id int32 `json:"id,omitempty"`

	Iso2 string `json:"iso2,omitempty"`

	Iso3 string `json:"iso3,omitempty"`

	Name string `json:"name,omitempty"`
}
