/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CouponDefinition struct {

	Code string `json:"code,omitempty"`

	Description string `json:"description,omitempty"`

	DiscountType string `json:"discount_type,omitempty"`

	Exclusive bool `json:"exclusive,omitempty"`

	MaxDiscount float64 `json:"max_discount,omitempty"`

	MaxQuantity int32 `json:"max_quantity,omitempty"`

	MinCartTotal float64 `json:"min_cart_total,omitempty"`

	Name string `json:"name,omitempty"`

	TargetItemId int32 `json:"target_item_id,omitempty"`

	Type_ string `json:"type,omitempty"`

	ValidForTags []string `json:"valid_for_tags,omitempty"`

	Value float64 `json:"value,omitempty"`

	VendorId int32 `json:"vendor_id,omitempty"`
}
