/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CreatePayPalPaymentRequest struct {

	// The endpoint URL to which PayPal should forward the user to if they cancel the checkout process
	CancelUrl string `json:"cancel_url,omitempty"`

	// The ID of an invoice to pay
	InvoiceId int32 `json:"invoice_id,omitempty"`

	// The endpoint URL to which PayPal should forward the user after they accept. This endpoint will receive information needed for the next step
	ReturnUrl string `json:"return_url,omitempty"`
}
