/* 
 * Knetik Platform API Documentation Latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CurrencyResource struct {

	// Whether the currency is active. Default true
	Active bool `json:"active,omitempty"`

	// The unique id code for the currency. Maximum 5 characters
	Code string `json:"code,omitempty"`

	// The unix timestamp in seconds the currency was added to the system
	CreatedDate int64 `json:"created_date,omitempty"`

	// The decimal to multiply the system base currency (from config 'currency') to localize to this one. Should be 1 for the base currency itself.
	Factor float64 `json:"factor,omitempty"`

	// The url for an icon of the currency
	Icon string `json:"icon,omitempty"`

	// The name of the currency
	Name string `json:"name,omitempty"`

	// The type of currency. Default 'real'
	Type_ string `json:"type,omitempty"`

	// The unix timestamp in seconds the currency was last updated in the system.
	UpdatedDate int64 `json:"updated_date,omitempty"`
}
