/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CustomerConfig struct {

	Aliases string `json:"aliases,omitempty"`

	Database DatabaseConfig `json:"database,omitempty"`

	Name string `json:"name,omitempty"`

	S3Config S3Config `json:"s3_config,omitempty"`
}
