/* 
 * Knetik Platform API Documentation Latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CustomerConfig struct {

	Aliases string `json:"aliases,omitempty"`

	Database DatabaseConfig `json:"database,omitempty"`

	Name string `json:"name,omitempty"`

	UploadBucket string `json:"upload_bucket,omitempty"`
}
