/* 
 * Knetik Platform API Documentation Latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type DatabaseConfig struct {

	Mongo MongoDatabaseConfig `json:"mongo,omitempty"`

	Sql SqlDatabaseConfig `json:"sql,omitempty"`
}
