/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type EventContextResource struct {

	EventName string `json:"event_name,omitempty"`

	Parameters map[string]ExpressionResource `json:"parameters,omitempty"`

	Type_ string `json:"type,omitempty"`
}
