/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type FattMerchantPaymentMethod struct {

	Address1 string `json:"address1,omitempty"`

	Address2 string `json:"address2,omitempty"`

	AddressCity string `json:"address_city,omitempty"`

	AddressCountry string `json:"address_country,omitempty"`

	AddressState string `json:"address_state,omitempty"`

	AddressZip string `json:"address_zip,omitempty"`

	// Last four digits of the credit card
	CardLastFour string `json:"card_last_four"`

	CreatedAt string `json:"created_at,omitempty"`

	// Unique FattMerchant customer ID
	CustomerId string `json:"customer_id"`

	DeletedAt string `json:"deleted_at,omitempty"`

	Id string `json:"id,omitempty"`

	// Nickname given to the FattMerchant payment method
	Nickname string `json:"nickname"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
