/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type FinalizePayPalPaymentRequest struct {

	// The ID of the invoice that is being paid. Must match the invoice sent in originally
	InvoiceId int32 `json:"invoice_id"`

	// The ID of the payer that PayPal returned with the user at the return URL
	PayerId string `json:"payer_id"`

	// The token that PayPal returned with the user in the return URL
	Token string `json:"token"`
}
