/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type GroupMember struct {

	Group Group `json:"group,omitempty"`

	Secondary bool `json:"secondary,omitempty"`

	Status string `json:"status,omitempty"`

	User User `json:"user,omitempty"`
}
