/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Language struct {

	Code string `json:"code,omitempty"`

	DateCreated int64 `json:"date_created,omitempty"`

	DateUpdated int64 `json:"date_updated,omitempty"`

	Description string `json:"description,omitempty"`

	Direction string `json:"direction,omitempty"`

	Id int32 `json:"id,omitempty"`

	IsPrimary bool `json:"is_primary,omitempty"`

	Name string `json:"name,omitempty"`
}
