/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type LeaderboardResource struct {

	// The paginated list of user results, in order from best to worst
	Entries []LeaderboardEntryResource `json:"entries,omitempty"`

	// The id of the leaderboard
	Id int64 `json:"id,omitempty"`

	// The name of the strategy that defines how entries are stored and compared
	Strategy string `json:"strategy,omitempty"`
}
