/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type MessageTemplateResource struct {

	// The content of the template. See Apache Velocity documentation for formatting
	Content string `json:"content"`

	// The id of the template. Cannot be changed after creation. default: auto generated
	Id string `json:"id,omitempty"`

	// The name of the template
	Name string `json:"name"`

	// A list of tags for search purposes. Will be converted to lower case
	Tags []string `json:"tags,omitempty"`
}
