/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type MessageResource struct {

	// The content of the message in various formats
	Content *MessageContentResource `json:"content"`

	// The id of the recipient, dependent on the recipient_type. The user's id or the topic's id. Required if sending directly to messaging service
	Recipient string `json:"recipient,omitempty"`

	// The type of recipient for the message. Either a user, or all users in a topic. Required if sending directly to messaging service
	RecipientType string `json:"recipient_type,omitempty"`

	// The subject of the message. Required for email messages
	Subject string `json:"subject,omitempty"`

	// The type of message for websocket type hinting. will be added to the payload with the key _type
	Type_ string `json:"type,omitempty"`
}
