/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ReactivateSubscriptionRequest struct {

	// The inventory to reactivate. Only required if using the deprecated subscriptions service
	InventoryId int32 `json:"inventory_id,omitempty"`

	// Whether to add the additional reactivation fee in addition to the recurring fee
	ReactivationFee bool `json:"reactivation_fee,omitempty"`
}
