/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type RevenueCountryReportResource struct {

	Country string `json:"country,omitempty"`

	Revenue float64 `json:"revenue,omitempty"`

	Volume int64 `json:"volume,omitempty"`
}
