/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type SimpleReferenceResourceint struct {

	// The id of the referenced object
	Id int32 `json:"id,omitempty"`

	// The name of the referenced object
	Name string `json:"name,omitempty"`
}
