/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type StripeCreatePaymentMethod struct {

	// Additional optional details to store on the payment method. If included, all fields in the details will override any defaults
	Details *PaymentMethodDetails `json:"details,omitempty"`

	// A token from Stripe to identify payment info to be tied to the customer
	Token string `json:"token"`

	// The id of the user, if null the logged in user is used. Admin privilege need to specify other users
	UserId int32 `json:"user_id,omitempty"`
}
