/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type SubscriptionPlan struct {

	AdditionalProperties map[string]Property `json:"additional_properties,omitempty"`

	Availability string `json:"availability,omitempty"`

	BillGraceDays int32 `json:"bill_grace_days,omitempty"`

	Consolidated bool `json:"consolidated,omitempty"`

	FirstBill int32 `json:"first_bill,omitempty"`

	FirstBillUnitOfTime string `json:"first_bill_unit_of_time,omitempty"`

	Id string `json:"id,omitempty"`

	LatePaymentSku string `json:"late_payment_sku,omitempty"`

	Locked bool `json:"locked,omitempty"`

	MaxAutoRenew int32 `json:"max_auto_renew,omitempty"`

	MaxBillAttempts int32 `json:"max_bill_attempts,omitempty"`

	MigrationPlan string `json:"migration_plan,omitempty"`

	MinimumTerm int32 `json:"minimum_term,omitempty"`

	Name string `json:"name,omitempty"`

	PrimarySku string `json:"primary_sku,omitempty"`

	ReactivationSku string `json:"reactivation_sku,omitempty"`

	RecurringSku string `json:"recurring_sku,omitempty"`

	RenewPeriod int32 `json:"renew_period,omitempty"`

	RenewPeriodUnitOfTime string `json:"renew_period_unit_of_time,omitempty"`

	SubscriptionId int32 `json:"subscription_id,omitempty"`
}
