/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type TemplatedEmail struct {

	// The external template ID used by the email provider
	ExternalTemplateId string `json:"external_template_id,omitempty"`

	// The map of data used by the template
	TemplateData *interface{} `json:"template_data,omitempty"`
}
