/* 
 * Knetik Platform API Documentation Latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type UserAchievementResource struct {

	// Flag indicating whether the user has earned the achievement
	Achieved bool `json:"achieved,omitempty"`

	// The achievement being tracked.  If used for Leveling, this represents the tier name
	AchievementName string `json:"achievement_name,omitempty"`

	// The date/time this resource was created in seconds since unix epoch
	CreatedDate int64 `json:"created_date,omitempty"`

	// The date/time the achievement was earned as a unix timestamp in seconds
	EarnedDate int64 `json:"earned_date,omitempty"`

	// The date/time this resource was last updated in seconds since unix epoch
	UpdatedDate int64 `json:"updated_date,omitempty"`
}
