/* 
 * Knetik Platform API Documentation Latest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type VideoTag struct {

	Id int64 `json:"id,omitempty"`

	Tag string `json:"tag,omitempty"`

	Video Video `json:"video,omitempty"`
}
