/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type WalletAlterRequest struct {

	// The amount of currency to add/remove. positive to add, negative to remove
	Delta float64 `json:"delta"`

	// The id of an invoice to attribute the transaction to
	InvoiceId int32 `json:"invoice_id,omitempty"`

	// The admin entered or system generated reason
	Reason string `json:"reason"`

	// The transaction type to allow for search/etc
	Type_ string `json:"type,omitempty"`
}
